### ISSUE TITLE
Use full paths to core Unix commands in functions

### ISSUE THREAD

**Issue by jfrazee** [reitzig/sdkman-for-fish#23]
The sdk functions currently assume that the standard Unix commands are first on the path and unaliased (e.g., [conf.d/sdk.fish#L45](https://github.com/reitzig/sdkman-for-fish/blob/master/conf.d/sdk.fish#L45)), so if you have something like `rm` aliased to `'rm -i'`, running `sdk` will prompt you every time with:

    rm: remove regular file '/tmp/tmp.OvvGBzqDYa'? y

This can be fixed by using the full paths to any standard Unix commands (e.g., `/bin/rm $pipe` instead of `rm $pipe`).

**Comment by reitzig** [comment]
Discussions about whether it's smart to alias standard GNU tools (which I assume breaks many a script and program), is that really a robust fix? Different installations might store binaries in different places.

Is `/usr/bin/env` standard enough to use it instead?

Not sure if any of these replacement assumptions is more minimal than "vanilla GNU tools are on the PATH". :/

**Comment by danielporto** [comment]
just found another problem related to this.
on OSX stat doesnt work like the unix version. Instead, it is required to use gstat
One recommended setting would be create an alias to stat with gstat and then solve the compatibility issue.
I couldn't find a way to make fish load these alias before calling sdk.fish thus I had to edit the file directly:
sdk.fish:if not set -q SDKMAN_DIR; or test (stat -c "%U" $SDKMAN_DIR) != (whoami)
to
sdk.fish:if not set -q SDKMAN_DIR; or test (gstat -c "%U" $SDKMAN_DIR) != (whoami)

it seems that this problem is more general and affects OSX users with standard configurations.

**Comment by reitzig** [comment]
@danielporto, the fact that macOS has a version of `stat` that's incompatible with GNU's is unfortunate but I don't think it has anything to do with the issue @jfrazee put forth. 
--> #28

**Comment by jfrazee** [comment]
@reitzig @danielporto OS X doesn't have `gstat` by default either so I think it'd create an even less desirable situation.

**Comment by reitzig** [comment]
I'm calling it, for now: this won't be fixed. We require GNU-ish tools on the PATH.

May reconsider if more issues and/or use cases pop up.

**Comment by reitzig** [comment]
I still don't understand why people would alias new tools and/or parameterized calls to standard tools to the names of standard tools. Fact is, they keep stumbling over this, and our code here doesn't behave well in such situations (implicit assumption on how the called commands work, what can I say).

Since I'm generally in favor of replacing some of the decades-old CLI cruft with non-drop-in-replacements (again: just don't pretend it is?!) -- something the shell scripting verse is clearly not ready for? -- and also of customizing your shell, I'm reopening this. Can't promise to act on it anytime soon, though.

In the meantime, I'm happy to review and merge a PR that

- adds meaningful tests that cover the change in behaviour, and
- handles _all_ direct calls to other programs one way or another -- we're up to at least `rm`, `cat`, `ls`, and why leave stragglers around?.

Adding `command` seems a feasible fix, but we may also want to replace some external dependencies with a little fish scripting (looking at _you_, `awk`!).
